name: Install, Lint, Format, Test

on:
  push:
    branches: [ "v0.9.1" ]
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: pip install ruff pytest
    - name: Lint
      run: ruff check
    - name: Format
      run: ruff format --check
    - name: Test
      run: pytest tests -v --run-all